config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get '/posts/index'
  get '/users/index'
  # Defines the root path route ("/")
  root 'users#index'
  # Defines the route for the users index page ("/users")
  resources :users, ony: [:index, :show] do
    # Defines the routel for the posts index page ("/users/:user_id/posts")
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resources :likes, only: [:create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable , :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy

  # validates :name, presence: true
  # validates :postsCounter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApplicationController
  before_action :set_author, only: [:show]
  def index
    authors = User.all.order(:id)
    render json: authors, status: :ok
  end

  def show
    render json: @author, status: :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/index.html.erb
<h1 class="text-center mt-2">List of all users</h1>
<% if @users.empty? %>
<div class="mt-3 d-flex align-items-center flex-column">
  <div class="card mb-3 border-danger" style="width: 540px">
    <div class="card-header bg-danger text-white">No User Found</div>
    <div class="card-body">
      <h5 class="card-title text-danger">
        There is no user please come again.
      </h5>
    </div>
  </div>
</div>
<% end %>
<div class="mt-3 d-flex align-items-center flex-column">
  <div style="width: 540px">
    <% @users.each do |user| %>
    <div class="card mb-3 border-primary" style="width: 680px">
      <div class="col-md-3">
        <img src="<%= user.photo %>" alt="avatar" />
      </div>
      <div class="mt-3 d-flex align-items-center flex-column">
        <h2 class="card-title"><%= link_to user.name , user %></h2>
        <p class="d-flex justify-content-end text-muted" style="width: 350px">
          Number of posts: <%= user.postsCounter %>
        </p>
      </div>
    </div>
    <% end %>
  </div>

  <%= button_to 'logout', destroy_user_session_path, data: {turbo: false},
  method: :delete %>
</div>

app/views/users/show.html.erb
<div class="mt-3 d-flex align-items-center flex-column">
  <div class="photo-name">
    <div class="card mb-3 border-primary" style="width: 180px">
      <img src="<%= @user.photo %>" alt="avatar" />
    </div>
    <div class="card-body">
      <h2><%= @user.name %></h2>
    </div>
    <div class="d-flex justify-content-end" style="width: 350px">
      <p class="card-text">
        <small class="text-muted"
          >Number of posts: <%= @user.postsCounter %></small
        >
      </p>
    </div>
  </div>
  <div class="card mb-3 border-info" style="width: 680px">
    <h1 class="card-header bg-info">Bio</h1>
    <div class="card-body">
      <p class="card-text"><%= @user.bio %></p>
    </div>
  </div>
</div>
<div>
  <div class="mt-3 d-flex align-items-center flex-column">
    <h2 class="card-title bg-info">Most Recent Posts</h2>
    <div class="card mb-3 border-danger" style="width: 680px">
      <% @user.most_recent_posts.each do |post| %> <%= link_to post.title,
      user_post_path(@user, post) %>
      <ul class="card-body">
        <li class="card-text"><%= post.text %></li>
      </ul>
      <div class="card-footer d-flex gap-2 justify-content-end">
        <p class="card-text">
          <small class="text-muted"
            >Comments: <%= post.comments_counter %></small
          >
          <!-- Link to comment path -->
        </p>
        <p class="card-text">
          <small class="text-muted">Likes: <%= post.likes_counter %></small>
        </p>
      </div>
      <% end %> <%= link_to "See All Posts ", user_posts_path(@user) , class:
      "btn btn-secondary" %>
    </div>
  </div>
</div>