config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get '/posts/index'
  get '/users/index'
  # Defines the root path route ("/")
  root 'users#index'
  # Defines the route for the users index page ("/users")
  resources :users, ony: [:index, :show] do
    # Defines the routel for the posts index page ("/users/:user_id/posts")
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create]
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, foreign_key: :post_id, dependent: :destroy
  has_many :comments, foreign_key: :post_id, dependent: :destroy

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  # validates :title, presence: true, length: { maximum: 250 }
  # validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  # validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def most_recent_comments
    comments.order(created_at: :desc).includes(:post).limit(5)
  end

  def update_posts_count_when_destroy
    author.decrement!(:postsCounter)
  end

  private

  def update_post_counter
    author.increment!(:postsCounter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  before_action :set_post, only: [:show]
  before_action :set_author, only: %i[index show]
  def index
    posts = @author.posts
    render json: posts, status: :ok
  end

  def show
    render json: @post, status: :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = User.find(params[:user_id])
  end

  def set_post
    @post = set_author.posts.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comments = @post.comments.includes(:author)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_post_path(current_user, @post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy
    if @post.destroy
      @post.update_posts_count_when_destroy
      redirect_to user_posts_path(current_user.id), notice: 'Post deleted successfully'
    else
      render :new, status: :unprocessable_entity, alert: 'Something'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<% @title='My Blog | Posts' %>
<div class="mt-3 d-flex align-items-center flex-column">
  <div class="card mb-3 border-primary" style="width: 680px">
    <div class="row g-0">
      <div class="col-md-3">
        <img
          src="<%= @user.photo %>"
          class="img-fluid rounded-start"
          alt="..."
        />
      </div>
      <div class="col-md-4">
        <div class="card-body">
          <h2 class="card-title"><%= @user.name %></h2>
        </div>
        <div class="d-flex justify-content-end" style="width: 350px">
          <p class="card-text">
            <small class="text-muted"
              >Number of posts: <%= @user.postsCounter %></small
            >
          </p>
        </div>
      </div>
    </div>
  </div>

  <p class="card-text">
    <%= link_to "New Post", new_user_post_path(user_id: @user.id), class: 'btn
    btn-primary ', style: "width: 320px" %>
  </p>
  <h4>Posts</h4>
  <% if @posts.empty? %>
  <div class="card mb-3 border-danger" style="width: 540px">
    <div class="card-header bg-danger text-white">No Post Found</div>
    <div class="card-body">
      <h5 class="card-title text-danger">
        Please first submit a post then come back to this page thanks.
      </h5>
    </div>
  </div>
  <% else %> <% @posts.each do |post| %> <%= link_to user_post_path(id:
  post.id), class:'nav-link' do%>
  <div class="card mb-3 border-success" style="width: 540px">
    <h1 class="card-header bg-success text-white"><%= post.title %></h1>
    <div class="card-body">
      <p class="card-text"><%= post.text.slice(0,70)%> ...</p>
    </div>
    <!-- Lin to new Post  -->
    <div class="d-flex justify-content-end" style="width: 530px">
      <div
        class="card-footer d-flex gap-2 justify-content-end"
        style="width: 530px"
      >
        <p class="card-text">
          <small class="text-muted"
            >Comments: <%= post.comments_counter %></small
          >
        </p>
        |
        <p class="card-text">
          <small class="text-muted">Likes: <%= post.likes_counter %></small>
        </p>
      </div>
    </div>
    <% end %>
    <div>
      <!-- ADD new like  -->
      <div class="mt-3 d-flex gap-1 justify-content-end">
        <div>
          <%= form_with model: @like, url: user_post_likes_path(post_id:
          post.id), class: 'form' do |f|%> <%= f.submit "Like", class:"btn
          btn-primary" %> <% end %>
        </div>
        <div>
          <button
            class="btn btn-primary"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapseExample"
            aria-expanded="false"
            aria-controls="collapseExample"
          >
            Add Comment
          </button>
        </div>
      </div>
    </div>
    <%= render partial: "shared/modal", locals: {post: post} %>

    <h4>Recent Comments</h4>
    <% if post.most_recent_comments.empty? %>
    <div class="card mb-3 border-danger" style="width: 540px">
      <div class="card-body">
        <p class="card-text">No Comments Found</p>
      </div>
    </div>
    <% else %>
    <div class="card mb-3 border-secondary" style="width: 540px">
      <div class="card-body">
        <% post.most_recent_comments.each do |comment| %>
        <p class="card-text"><%= comment.author.name %>: <%= comment.text %></p>
        <% end %>
      </div>
    </div>
    <% end %> <% end %> <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div>
  <!-- Add new Post -->
  <div class="mt-3 d-flex align-items-center flex-column">
    <h1>Add new Post</h1>
    <%= form_with model: @post, url: user_posts_path, method: :post, class:
    'form' do |f|%> <%= f.text_field :title, class:"form-control" %>
    <br />
    <%= f.text_area :text, class:"form-control" %>
    <br />
    <%= f.submit "Post", class:"btn btn-primary" %> <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% @title="My Blog | #{@post.title}" %>
  <div class='mt-3 d-flex align-items-center flex-column'>
    <div class="card mb-3 border-success" style="width: 670px;">
      <div class="card-header bg-success text-white">
        <div class='row'>
          <div class='col-md-8'>
            <%= @post.title %> by <%= @user.name %>
          </div>
          <div class='col-md-4 d-flex gap-2'>
            <p class="card-text"><small class="text-white">Comments: <%= @post.comments_counter %></small></p>
            |
            <p class="card-text"><small class="text-white">Likes: <%= @post.likes_counter %></small></p>
          </div>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text">
          <%= @post.text%>
        </p>
      </div>
      <% if can? :destroy, @post %>
        <div class="card-footer">
          <%= link_to "Delete" , user_post_path(user_id: @user.id, id: @post.id), "data-turbo-method": :delete, class: 'btn btn-danger' %>
        </div>
        <% end %>
    </div>
    <h3>Comments</h3>
    <% if @comments.empty? %>
      <div class="card mb-3 border-danger" style="width: 670px;">
        <div class="card-body">
          <p class="card-text text-danger">No Comment Found</p>
        </div>
      </div>
      <% else %>
        <div class="card mb-3 border-secondary" style="width: 670px;">
          <div class="card-body">
            <% @comments.each do |comment| %>
              <p class="card-text d-flex justify-content-between">
                <%= comment.author.name %>: <%= comment.text %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical  " viewBox="0 0 16 16"             data-bs-toggle="collapse"
                data-bs-target="#collapseExample"             aria-expanded="false"
                aria-controls="collapseExample" >
                  <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                </svg>
                
                   
              </p>
              <div class="collapse" id="collapseExample">
                  <div class="mt-3 mb-5 d-flex justify-content-end">
                    <% if can? :destroy, comment %>
                    <%= link_to "Delete" , user_post_comment_path(user_id: @user.id, post_id: @post.id, id:
                      comment.id), "data-turbo-method": :delete, class: 'btn btn-danger'%>
                      <% end %>
                  </div>
                </div>
              <% end %>
          </div>
        </div>
        <% end %>
  </div>